### ISSUE TITLE
SyntaxError: Invalid regular expression on test script

### ISSUE THREAD

**Issue by emosGambler** [Microsoft/BosqueLanguage#141]
**Describe the bug**
When running comand:
`
npm install && npm run-script build && npm test
`
it gives me syntax error:

 bosque-reference-implementation@0.0.1 build /home/emos/programming/BosqueLanguage/ref_impl
 tsc -p tsconfig.json

 bosque-reference-implementation@0.0.1 test /home/emos/programming/BosqueLanguage/ref_impl
 tsc -p tsconfig.json && node ./bin/test/test_runner.js

/home/emos/programming/BosqueLanguage/ref_impl/bin/ast/parser.js:326
Lexer._s_commentRe = /\/(?:\/[^\n\r]*|\*(?<multiline>[^\*]*\**)+?(?<multilineEndChar>\/|$))/y;
^

SyntaxError: Invalid regular expression: /\/(?:\/[^\n\r]*|\*(?<multiline>[^\*]*\**)+?(?<multilineEndChar>\/|$))/: Invalid group
    at Object.<anonymous> (/home/emos/programming/BosqueLanguage/ref_impl/bin/ast/parser.js:326:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/emos/programming/BosqueLanguage/ref_impl/bin/compiler/mir_emitter.js:7:18)
    at Module._compile (module.js:652:30)
npm ERR! Test failed.  See above for more details.

**To Reproduce**
Run the command above in `ref_impl/` directory

**Expected behavior**
Tests should just fire up.

**Desktop:**
 - OS: Ubuntu
 - Master

**Comment by clegoz** [comment]
Which version of nodejs you're using?
I've just tested on v10.14.2 everything looks fine.

**Comment by raphaelkieling** [comment]
I use Node v11.11.0 and everything looks fine too

**Comment by emosGambler** [comment]
Hey! My node was v8.1. After updating it all get fixed :). Thank you, guys!
