### ISSUE TITLE
Syntax error with "max.bsq" README.md example

### ISSUE THREAD

**Issue by igouy** [microsoft/BosqueLanguage#220]
```
$ node /opt/src/bosque/BosqueLanguage/ref_impl/src/runtimes/exegen/exegen.ts -o max.exe max.bsq
/opt/src/bosque/BosqueLanguage/ref_impl/src/runtimes/exegen/exegen.ts:6
import * as FS from "fs";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:881:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11
```

Linux x64 5.3.0-26-generic # 28-Ubuntu SMP
node v12.11.0
tsc 3.6.3

**Comment by igouy** [comment]
`    "type": "module"`
```

$ node --experimental-modules /opt/src/bosque/BosqueLanguage/ref_impl/src/runtimes/exegen/exegen.ts -o max.exe max.bsq
(node:9029) ExperimentalWarning: The ESM module loader is experimental.
file:///opt/src/bosque/BosqueLanguage/ref_impl/src/runtimes/exegen/exegen.ts:20
function generateMASM(files: string[], corelibpath: string): MIRAssembly {
                           ^

SyntaxError: Unexpected token ':'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:82:18)
    at async link (internal/modules/esm/module_job.js:38:36)
```

**Comment by mrkmarron** [comment]
Looks like you are trying to load the `.ts` files into node directly. You need to run the typescript compiler and load the resulting `.js` files.
