### ISSUE TITLE
tsc -p tsconfig.json in package.json throws error

### ISSUE THREAD

**Issue by evan-a-west** [Microsoft/BosqueLanguage#47]
When running the command  `npm run-script build`, the error, below, is thrown. There seems to be an issue with the `tsc -p tsconfig.json` line in package.json. 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle bosque-reference-implementation@0.0.1~prebuild: bosque-reference-implementation@0.0.1
6 info lifecycle bosque-reference-implementation@0.0.1~build: bosque-reference-implementation@0.0.1
7 verbose lifecycle bosque-reference-implementation@0.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle bosque-reference-implementation@0.0.1~build: PATH: <lots of local paths>
9 verbose lifecycle bosque-reference-implementation@0.0.1~build: CWD: <custom_directory>\BosqueLanguage\ref_impl
10 silly lifecycle bosque-reference-implementation@0.0.1~build: Args: [ '/d /s /c', 'tsc -p tsconfig.json' ]
11 silly lifecycle bosque-reference-implementation@0.0.1~build: Returned: code: 1  signal: null
12 info lifecycle bosque-reference-implementation@0.0.1~build: Failed to exec build script
13 verbose stack Error: bosque-reference-implementation@0.0.1 build: `tsc -p tsconfig.json`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid bosque-reference-implementation@0.0.1
15 verbose cwd <custom_directory>\BosqueLanguage\ref_impl
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "build"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error bosque-reference-implementation@0.0.1 build: `tsc -p tsconfig.json`
22 error Exit status 1
23 error Failed at the bosque-reference-implementation@0.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

 running  `tsc -p tsconfig.json` on it's own yields the error: 

`error TS5023: Unknown option 'p'
Use the '--help' flag to see options.
error TS5007: Cannot resolve referenced file: 'tsconfig.json'.`

I newly installed the latest x64bit LTS version of Node.js (its been awhile since I last used it).
`node -v` yields v10.15.3
`npm -v` yields 6.4.1
`tsc -v` yields 1.0.1.0

Is this an issue with the package.json? The current LTS version of Node.js does not seem to have '-p' as an option. The mann page for tsc does not show a '-p' option

**Comment by evan-a-west** [comment]
No Issue exists, user error.

I deleted `C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\ ` from my path so that the npm version of typescript was utilized. 

`tsc -v` now yields Version 3.4.4 and 'npm run-script build' runs without issue.
